version: "2.0"

# This override file adds Caddy reverse proxy with automatic HTTPS/TLS
# To use it:  docker-compose -f docker-compose.yml -f docker-compose.caddy.yml up -d
# Or rename it to docker-compose.override.yml for automatic inclusion

services:
  caddy:
    image: ${CADDY_IMAGE:-caddy:latest}
    container_name: glkvm_caddy
    restart: always
    ports:
      # HTTP for ACME challenges and automatic redirect to HTTPS
      - "80:80"
      # HTTPS for secure access
      - "443:443"
      - "443:443/udp"  # HTTP/3 support
      # HTTP Proxy port (proxied by Caddy with TLS)
      - "10443:10443"
    volumes:
      - ./templates/Caddyfile.template:/tpl/Caddyfile.tmpl:ro
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: ${DOMAIN}
      ACME_EMAIL: ${ACME_EMAIL}
      RTTYS_WEBUI_INTERNAL_PORT: ${RTTYS_WEBUI_INTERNAL_PORT:-8443}
      RTTYS_HTTP_PROXY_INTERNAL_PORT: ${RTTYS_HTTP_PROXY_INTERNAL_PORT:-18443}
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]
    command: ["caddy"]
    depends_on:
      - rttys

  # When Caddy is used, rttys uses internal ports that Caddy will proxy to
  # Caddy will handle the HTTPS and proxy to rttys internal ports
  rttys:
    environment:
      # Override ports to use internal ports when behind Caddy
      RTTYS_WEBUI_PORT: ${RTTYS_WEBUI_INTERNAL_PORT:-8443}
      RTTYS_HTTP_PROXY_PORT: ${RTTYS_HTTP_PROXY_INTERNAL_PORT:-18443}
    # Override volumes to exclude SSL certificates
    # When using Caddy, rttys should run in HTTP mode (no SSL)
    # Caddy terminates TLS and proxies to rttys over HTTP
    # Note: The !override tag is a Docker Compose merge control that completely replaces
    # the entire volumes array from the base docker-compose.yml (not just specific entries).
    # We only keep the template and entrypoint volumes needed for configuration.
    # The SSL certificate volumes from the base docker-compose.yml are intentionally excluded.
    volumes: !override
      - ./templates/rttys.conf.template:/tpl/rttys.conf.tmpl:ro
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    # Use !override to replace the entire ports section from base docker-compose.yml
    # This prevents Docker Compose from merging arrays and ensures only port 5912 is exposed
    ports: !override
      # Only expose device connection port - do not expose web UI or HTTP proxy ports
      # as Caddy will handle those
      - "${RTTYS_DEVICE_PORT:-5912}:${RTTYS_DEVICE_PORT:-5912}"

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
